### ISSUE TITLE
Your nick is written wrong

### ISSUE THREAD

**Issue by PhantomDave** [BigETI/SAMPLauncherNET#48]
I started using this launcher a few days ago, but it just keep giving me an error when i try to start the game.

I Checked that my name is simply "Dave" Without spaces.

![immagine](https://user-images.githubusercontent.com/34485699/39094999-521224a4-4639-11e8-870f-c83665742333.png)

**Comment by BigETI** [comment]
This dialog is not invoked from this launcher either.

**Comment by PhantomDave** [comment]
From the process list it seems invoked from gta_sa.exe, but the normal SAMP launcher start normally

**Comment by PhantomDave** [comment]
From the process list it seems invoked from gta_sa.exe, but the normal SAMP launcher start normally

**Comment by BigETI** [comment]
Any spaces should have been cut off at launch, because the username is inserted as a command line argument, which should trim the username in the first place. The first white space between two characters should have cut off the rest of the username.
This dialog isn't available at this launcher or samp.dll.
This might have been caused by 3rd party modifications to your SA:MP installation.

**Comment by BigETI** [comment]
Anyone who encounters this issue, this is caused by SAMP Addon.

The reason behind is not the launcher itself, but how command line arguments are being parsed on the SAMP Addon part,
which is against the utility conventions.

Source: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

> Guideline 6:
>     Each option and option-argument should be a separate argument, except as noted in [Utility Argument Syntax](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_01), item (2).
